# Generated by Django 5.0 on 2024-01-31 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_article_author_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='article',
        ),
    ]
