# Generated by Django 5.0 on 2024-01-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_choice_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Engineer',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.DeleteModel(
            name='MyModels',
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('NW', 'New'), ('RJ', 'Rejected'), ('AP', 'Approved')], default='NW', max_length=2),
        ),
    ]
